version: "3.8"
services:
  ngrok:
    image: ngrok/ngrok
    container_name: ngrok
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: http github_webhook_server:5000
    ports:
      - "4040:4040"
    restart: unless-stopped

  firefox:
    image: selenium/standalone-firefox:4.1.2-20220131
    container_name: firefox
    restart: unless-stopped
    environment:
      START_XVFB: "false"
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - ngrok
    healthcheck:
      test: [ "CMD", "/opt/bin/check-grid.sh", "--host", "0.0.0.0", "--port", "4444" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "4444:4444"

  github_webhook_server:
    container_name: github_webhook_server
    build: github-webhook-server-container
    depends_on:
      - ngrok
      - firefox
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_OWNER=${GITHUB_OWNER}
      - GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
      - FLASK_DEBUG=1
    ports:
      - "5000:5000"
    restart: unless-stopped
