repositories:
  openshift-python-wrapper:
    name: RedHatQE/openshift-python-wrapper
    token: <GITHIB TOKEN>
    verified_job: true
    events:  # To listen to all events do not send events
      - push
      - pull_request
      - issue_comment
